### ISSUE TITLE
Display: flex and media query not detected, failed test

### ISSUE THREAD

**Issue by Elkmar** [freeCodeCamp/testable-projects-fcc#1101]
#### Issue Description

I try to pass the tests to validate my projects with Google chrome, I've a section using flexbox, but the test does not find it and fail. Same for my media query. 

If I do the test in codepen, it works

#### Browser Information

- Browser Name, Version: Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)
- Operating System: MAC OS Catalina
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/Elkmar/pen/MWayLYM

```
@media print {
    body {
      color: black;
    }
  }

#apple-img {
    display: flex;
    width: 100%;
    margin-bottom: 2vw;
    grid-area: apple-img;
    justify-content: space-evenly;
}
```

#### Screenshot

<img width="1596" alt="Screenshot 2020-04-20 at 12 23 01" src="https://user-images.githubusercontent.com/29351769/79746336-b9955900-8301-11ea-88e7-e34610c6bf9a.png">

**Comment by tbrlpld** [comment]
I have the same issue on the Product Landing page.

Here is my CSS
```css
#nav-bar {
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-around;
}

@media screen (max-width: 300px) {
  #nav-bar {
    flex-direction: row;
  }
}

```
