### ISSUE TITLE
css pollution issues

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/testable-projects-fcc#23]
The project's CSS could use a bit of a refactor to prevent CSS pollution in both directions, both the project's CSS affecting the test suite, and the test suites CSS affecting projects, will need to take a look and see what other improvements can be made like in #22

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson So I've taken a look, and I think with the fix made from issue #22, the one about the `input[type="checkbox"]`, there are no other rules from the test suite's CSS that will pollute a projects CSS, however, enforcing the reverse is quite the challenge. 

If a user adds global styles to their projects using the `*` selector or something like:
```css
body {
    color: red; /* will affect text in foldaway menu  */
  h2 {
     border-bottom: 2px solid black; /* will affect test cases in mocha div */
  }
}
```
or:
```css
body span {
    margin: 100px; /* will affect items in the foldaway menu */
}
```
Any rules like these have the potential to affect the test suites styling. Was discussing this with @Weezlo at some point, and we were not sure of a good way to prevent this, aside from adding a warning in the boilerplate pen:
![image](https://cloud.githubusercontent.com/assets/18563015/22409326/2955bb96-e656-11e6-85e6-43d586bc7ce3.png)
