### ISSUE TITLE
[fCC Project Personal Portfolio] Welcome-section should be as high as the viewport

### ISSUE THREAD

**Issue by hungHoangDang** [freeCodeCamp/testable-projects-fcc#389]
#### Issue Description
Hi! I am working on this last project before jumping over to JavaScript. Anyway when I finished it and ran the test, it appeared that I passed 11 of the requirement and the last one is about **welcome-section should as high as the viewport**. I tried to Google and did as they said but nothing changed. If you somehow solved this issue and read this, please tell me what I should do. Much appreciated!

#### Browser Information

* Browser Name, Version: Chrome 67.0.3396.87
* Operating System: Window 7 Home Basic N (64bit)
* Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

This is my Codepen: https://codepen.io/matthewdang131/pen/zBROzX?editors=1000

This is the welcome section code:

```html 
        <div id="welcome-section">
            <div id="photo">
                <img id="My-image" src="http://res.cloudinary.com/hunghayho131/image/upload/v1529201842/Images/myImage.jpg">
            </div>
            <div id="info">
                <div class="info-box">
                    <h1>Dang Hoang Hung</h1>
                    <h3>Web Developer</h3>
                    <p>Hello! My name is Hung and I love building dynamic web apps that will solve real world problems</p>
                </div>
            </div>
        </div> 
```
And this is the css code for the welcome-section: 

```css
#My-image {
  border-radius: 50%;
  width: 20em;
}

#welcome-section {
  padding: 50px 0;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
  margin: 100px 0;
}

#info {
  padding-left: 20px;
}

.info-box {
  text-align: left;
}
```
#### Screenshot

![screenshot](https://user-images.githubusercontent.com/33661599/41805680-23b4472e-76d9-11e8-9a11-358edf89f645.jpg)
It didn't even properly show the screen shot but it's all I have.
