### ISSUE TITLE
Product Landing Page - Flexbox Test does not appear to be working properly

### ISSUE THREAD

**Issue by kelsiestevenson** [freeCodeCamp/testable-projects-fcc#521]
#### Issue Description
I am receiving the following error on my page:
```
AssertionError: We do not detect a display property set to flex or inline-flex anywhere in your CSS : expected 0 to be above 0
    at Function.n.isAbove (assets/test.js:160:789)
    at n.<anonymous> (assets/test.js:147:287160)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
```

The first few lines of my `css` look like this:
```css
/*****************************/
/**********Main***************/
/*****************************/

* {
    font-family: arial;
}
body {
    display: flex;
    flex-flow: column nowrap;
    margin: 0;
    width: 100vw;
    height: 100vh;
    max-width:100%;
}
```

I use flex frequently throughout the rest of my css yet the error is still visible

#### Browser Information

* Browser Name, Version: Google Chrome
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
Here is a snippet of my `css`. I am using GitPages so I cannot link to a Pen
```css
 /*****************************/
/**********Main***************/
/*****************************/

* {
    font-family: arial;
}
body {
    display: flex;
    flex-flow: column nowrap;
    margin: 0;
    width: 100vw;
    height: 100vh;
    max-width:100%;
}
img {
    justify-content: center;
    width: 100px;
}

h1, h2 {
    font-weight: lighter;
    color: darkslategray;
    padding: 0 20px 0 20px;
}

/*****************************/
/*******Nav Bar***************/
/*****************************/

#header-img {
    display: flex;
    position: fixed;
    display: inline-flex;
    z-index: 15;
    margin: 1em;
}

.navbar {
    display: flex;
    align-items: center;
    padding: 20px 0px;
    flex-flow: row nowrap;
    justify-content: flex-end;
    position: fixed;
    flex-shrink: 0;
    display: inline-flex;
    top: 0;
    width: 100%;
    overflow: hidden;
    background-color: darkorchid;
    z-index: 10;
}

```
