### ISSUE TITLE
Failing desktop id=navbar test on Technical Documentation Project

### ISSUE THREAD

**Issue by zargold** [freeCodeCamp/testable-projects-fcc#543]
#### Issue Description

Build a navbar (nav#navbar) with
``` css
#navbar {
    width: 100vw; //also tried width 100% or even 200vw
    display: block;
    position: fixed;
    top: 0;
    left: 0;
}
```
on window size 600px (also tried 768px)

#### Link to actual reproducing issue:

[codepen](https://codepen.io/zargold/pen/yEPaJq)

#### Browser Information

* Browser Name, Version: 
Chrome: Version 68.0.3440.106 (Official Build) (64-bit)
Also tried safari
* Operating System: Mac OSX 10.13.16
* Mobile, Desktop, or Tablet: 
Desktop 
#### Your Code / Link to Your Pen

In order to get the tests to pass I had to do:

``` css
#navbar {
    width: 100vw; //also tried width 100% or even 200vw
    display: block;
    position: fixed;
    top: 0;
    left: -100vw;
}
```

As a result of doing this it actually no longer matches the criteria of always being visible (it is never visible but it doesn't know that.
#### Screenshot

<img width="1021" alt="screen shot 2018-08-21 at 7 40 43 am" src="https://user-images.githubusercontent.com/11298496/44399432-922b2f00-a515-11e8-8c95-d3bd48531dde.png">
