### ISSUE TITLE
Unable to choose test suite with Materialize CSS

### ISSUE THREAD

**Issue by matthewsecrist** [freeCodeCamp/testable-projects-fcc#75]
#### Issue Description

When using Materialize as the CSS framework on Codepen, I am unable to select what test suite to run. Works fine when I remove Materialize.

#### Browser Information

* Browser Name, Version: Chrome 56.0 or Safari
* Operating System: MacOS Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

```
 http://codepen.io/msecrist/full/VPXMjw/
 
Also able to reproduce with the "Fork this pen!" example and adding https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css as external CSS.
 
```

#### Screenshot

<img width="367" alt="screen shot 2017-03-06 at 11 02 42 pm" src="https://cloud.githubusercontent.com/assets/11762308/23642595/6ad508a6-02c1-11e7-8ef0-428dce7b8a7a.png">

**Comment by christophherr** [comment]
This is due to Materialize setting `select` to `display: none;`
Even if that is corrected, the select field doesn't look good because Materialize additionally applies 
```css
select {
 background-color: rgba(255,255,255,0.9);
 width: 100%;
 padding: 5px;
 border: 1px solid #f2f2f2;
 border-radius: 2px;
 height: 3rem
}
```
Looks like `#fcc_foldout_menu select` would have to "counter" those styles.
